# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mp4d/git/BRAM-uio-driver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mp4d/git/BRAM-uio-driver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mp4d/git/BRAM-uio-driver/CMakeFiles /home/mp4d/git/BRAM-uio-driver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mp4d/git/BRAM-uio-driver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nn_test

# Build rule for target.
nn_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nn_test
.PHONY : nn_test

# fast build rule for target.
nn_test/fast:
	$(MAKE) -f CMakeFiles/nn_test.dir/build.make CMakeFiles/nn_test.dir/build
.PHONY : nn_test/fast

nn_test.o: nn_test.cpp.o

.PHONY : nn_test.o

# target to build an object file
nn_test.cpp.o:
	$(MAKE) -f CMakeFiles/nn_test.dir/build.make CMakeFiles/nn_test.dir/nn_test.cpp.o
.PHONY : nn_test.cpp.o

nn_test.i: nn_test.cpp.i

.PHONY : nn_test.i

# target to preprocess a source file
nn_test.cpp.i:
	$(MAKE) -f CMakeFiles/nn_test.dir/build.make CMakeFiles/nn_test.dir/nn_test.cpp.i
.PHONY : nn_test.cpp.i

nn_test.s: nn_test.cpp.s

.PHONY : nn_test.s

# target to generate assembly for a file
nn_test.cpp.s:
	$(MAKE) -f CMakeFiles/nn_test.dir/build.make CMakeFiles/nn_test.dir/nn_test.cpp.s
.PHONY : nn_test.cpp.s

src/bram_uio.o: src/bram_uio.cpp.o

.PHONY : src/bram_uio.o

# target to build an object file
src/bram_uio.cpp.o:
	$(MAKE) -f CMakeFiles/nn_test.dir/build.make CMakeFiles/nn_test.dir/src/bram_uio.cpp.o
.PHONY : src/bram_uio.cpp.o

src/bram_uio.i: src/bram_uio.cpp.i

.PHONY : src/bram_uio.i

# target to preprocess a source file
src/bram_uio.cpp.i:
	$(MAKE) -f CMakeFiles/nn_test.dir/build.make CMakeFiles/nn_test.dir/src/bram_uio.cpp.i
.PHONY : src/bram_uio.cpp.i

src/bram_uio.s: src/bram_uio.cpp.s

.PHONY : src/bram_uio.s

# target to generate assembly for a file
src/bram_uio.cpp.s:
	$(MAKE) -f CMakeFiles/nn_test.dir/build.make CMakeFiles/nn_test.dir/src/bram_uio.cpp.s
.PHONY : src/bram_uio.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... nn_test"
	@echo "... nn_test.o"
	@echo "... nn_test.i"
	@echo "... nn_test.s"
	@echo "... src/bram_uio.o"
	@echo "... src/bram_uio.i"
	@echo "... src/bram_uio.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

